### ISSUE TITLE
exporting config to Ixncfg format

### ISSUE THREAD

**Issue by subha-py** [OpenIxia/ixnetwork_client_python#11]
Hi @ajbalogh ,
Trying to export a config in **ixncfg** format rather than the default json version.
This piece of code is throwing error - 
Are we using in the correct way? Or is it a bug?

```
from ixnetwork import IxnHttp, IxnConfigManagement
ixnhttp = IxnHttp(host, rest_port=rest_port)
ixnhttp.auth('admin', 'admin')
ixnhttp.create_session()
# made a configuration
# now trying to export in ixncfg
config_mgmt = IxnConfigManagement(ixnhttp)
xpaths = [
			'/vport/descendant-or-self::*',
			'/topology/descendant-or-self::*',
			'/traffic/descendant-or-self::*'
		]
config_mgmt.export_config(xpaths=xpaths, local_filename=converted_filename,export_format = 'ixncfg')
```

**Comment by whandjr** [comment]
Subha, which api are you using?  Is it restpy?



Thanks,
Wes
(818) 312-6752

Sent via the Samsung Galaxy S8+, please excuse typos


-------- Original message --------

**Comment by whandjr** [comment]
Adding Hubert.

Hubert may already have a sample script that does what you need.

Can you check with him as well?

We recommend using restpy, not the legacy python api. Or a low level rest call.



Thanks,
Wes
(818) 312-6752

Sent via the Samsung Galaxy S8+, please excuse typos


-------- Original message --------

**Comment by ajbalogh** [comment]
There is an explicit method in IxnConfigManagement to save a configuration in ixncfg format called save_config..
