### ISSUE TITLE
Error while POST - ing  some pattern in multivalue object

### ISSUE THREAD

**Issue by subha-py** [OpenIxia/ixnetwork_client_python#3]
- Build used: 

Ixnetwork client: 8.40 EA

- Problem:

While performing post operation for some multivalue patterns - repeatableRandomRange, repeatableRandom.

Ixnetwork returns error.

- Example:

request type: **POST** 
URL: `/api/v1/sessions/<session_id>/ixnetwork/multivalue/<id>/random`
response: 
```
{
  "links": [
    {
      "rel": "self",
      "method": "GET",
      "href": "/api/v1/sessions/<session_id>/ixnetwork/multivalue/<id>/random"
    }
  ]
}
```

But for
request type: **POST**
URL: /`api/v1/sessions/<session_id>/ixnetwork/multivalue/<id>/repeatableRandomRange`
response: 
```
{
  "method": "POST",
  "pathAndQuery": "/api/v1/sessions/<session_id>/ixnetwork/multivalue/<id>/repeatableRandomRange",
  "errors": [
    {
      "code": 10000,
      "detail": "One of the identified items was in an invalid format."
    }
  ]
}

```

**Comment by ajbalogh** [comment]
IxnMultivalue.py has been modified to set the initial payload on creating repeatableRandom and repeatableRandomRange patterns.
The multivalue.py sample demonstrates the workaround by providing initial values to repeatableRandom and repeatableRandomRange.
Version 0.55a44 is available on pypi.
